### ISSUE TITLE
mac下载报错了

### ISSUE THREAD

**Issue by Nioy** [drunkdream/weread-exporter#101]
mac m1max  macos14

报错信息如下：
[2024-09-10 10:49:24,661][INFO]Exporting book adc32180813ab8786g014ba6
[2024-09-10 10:49:24,927][ERROR]Fetch url https://weread.qq.com/web/bookDetail/adc32180813ab8786g014ba6 failed
Traceback (most recent call last):
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1080, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/utils.py", line 38, in fetch
    async with session.get(url, headers=headers) as response:
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1082, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host weread.qq.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
[2024-09-10 10:49:25,192][ERROR]Fetch url https://weread.qq.com/web/bookDetail/adc32180813ab8786g014ba6 failed
Traceback (most recent call last):
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1080, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/utils.py", line 38, in fetch
    async with session.get(url, headers=headers) as response:
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1082, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host weread.qq.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
[2024-09-10 10:49:25,444][ERROR]Fetch url https://weread.qq.com/web/bookDetail/adc32180813ab8786g014ba6 failed
Traceback (most recent call last):
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1080, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/utils.py", line 38, in fetch
    async with session.get(url, headers=headers) as response:
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1082, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host weread.qq.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/__main__.py", line 158, in <module>
    main()
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/__main__.py", line 75, in async_main
    if not await page.check_valid():
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/webpage.py", line 144, in check_valid
    html = await utils.fetch(self._home_url)
  File "/Users/njy/pythonWorkspace/opensource/weread-exporter/weread_exporter/utils.py", line 48, in fetch
    raise RuntimeError("Fetch url %s failed" % url)
RuntimeError: Fetch url https://weread.qq.com/web/bookDetail/adc32180813ab8786g014ba6 failed

**Comment by ypz-git** [comment]
最近爬不了……

**Comment by BKDragon** [comment]
应该是都不行了。
