### ISSUE TITLE
加载书籍内容超时 load selector timeout

### ISSUE THREAD

**Issue by moleoxa** [drunkdream/weread-exporter#104]
安装完依赖后，运行提示没有 chrome，于是把 chrome 加入环境变量。

再次以 -- force-login 参数运行，成功拉起了 chrome，但是卡住在 about:blank 页，等待一段时间后会自动退出 chrome 并报错。

![图片](https://github.com/user-attachments/assets/aeed6a0d-d810-4250-a472-1357bd1994f9)

```
C:\Users\Administrator>python -m weread_exporter -b adc32180813ab8786g014ba6 -o epub
Fontconfig error: Cannot load default config file: No such file: (null)
[2024-09-28 17:50:41,239][INFO]Exporting book adc32180813ab8786g014ba6
[2024-09-28 17:50:41,440][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/adc32180813ab8786g014ba6
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\User\Desktop\test\weread-exporter-main\weread_exporter\__main__.py", line 158, in <module>
    main()
  File "D:\User\Desktop\test\weread-exporter-main\weread_exporter\__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\User\Desktop\test\weread-exporter-main\weread_exporter\__main__.py", line 85, in async_main
    await page.launch(headless=args.headless, force_login=args.force_login)
  File "D:\User\Desktop\test\weread-exporter-main\weread_exporter\webpage.py", line 175, in launch
    self._browser = await pyppeteer.launch(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

[2024-09-28 17:51:11,699][INFO]terminate chrome process...
```

**Comment by Estherbad** [comment]
一样的问题，你有解决方案了吗

**Comment by Kennethcd** [comment]
对，我之前可以，现在不行了，也是像你这样

**Comment by Amerio0902** [comment]
想问下解决了吗？我也是相似的问题,timeout,可以打开书籍页面，之后一直转圈，没法提取

<img width="1918" height="1077" alt="Image" src="https://github.com/user-attachments/assets/111dc5dd-3147-4f58-bff3-8fa2cbb78026" />
