### ISSUE TITLE
windows 10系统运行该项目遇到的两个问题以及解决办法

### ISSUE THREAD

**Issue by jiao-long** [drunkdream/weread-exporter#13]
**先说结论给大家打打气：该项目可以爬取微信读书上已购买的书籍，付费书籍需要购买才能完整爬取。**

### 项目使用过程中遇到的两个问题：
1、运行**python -m weread_exporter -b $book_id -o epub -o pdf**命令时报错，报错提示如下：
报错：
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**报错原因**：Python环境缺少这三个库：cairo-2、cairo、libcairo-2。如果使用以下命令直接安装这三个库还是会报错：
pip install pycairo
pip install cairocffi
pip install WeasyPrint
因为在Windows系统上安装WeasyPrint还需要其它步骤，而且我们只需要安装WeasyPrint，其它两个库在安装WeasyPrint的过程中会自动附带。

**报错1的解决办法：**
在Windows 10环境中安装WeasyPrint可以按照以下步骤进行：

①安装3.7版本以上的Python环境：访问Python官网（[https://www.python.org/downloads/windows/），下载并安装3.7版本以上的Python。（具体怎么安装网上找教程）

②安装GTK+运行时环境：WeasyPrint使用了GTK+和cairo库来实现渲染和布局，因此需要先安装GTK+运行时环境。访问GTK+官网（[https://www.gtk.org/docs/installations/windows/）或者github项目（https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases），下载并安装最新版本的GTK+运行时环境。

③安装WeasyPrint：在安装好Python和GTK+运行时环境后，可以使用以下命令来安装WeasyPrint（如果之前安装过就不用安装了）：

python -m pip install weasyprint

④测试安装是否成功：在安装完WeasyPrint后，可以使用以下命令来测试是否安装成功：

python -m weasyprint --version
如果安装成功，将输出WeasyPrint的版本号。

注意事项：

如果你在安装WeasyPrint时遇到了找不到libffi-7.dll的错误，请下载libffi-7.dll文件并将其放置在Python安装目录下的DLLs文件夹中。

WeasyPrint需要的是GTK+ 3.x版本，而不是GTK+ 2.x版本。因此，请确保安装的是GTK+ 3.x版本的运行时环境。
不确定以上步骤是否对Windows 11适用，Windows 11系统安装WeasyPrint，可以参考官网的windows部分（https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#cairo）

-----------------------------------------------------------------------------------------------------------------
2、安装完WeasyPrint后，执行命令**python -m weread_exporter -b $book_id -o epub -o pdf**报错：
Windows 10系统中提示文件找不到（FileNotFound）。mac系统中提示chrome找不到。

报错原因：没有配置Chrome浏览器的系统环境变量。

解决办法：将chrome.exe的目录配置在系统环境变量中。比如，我的谷歌浏览器路径是：C:\Program Files\Google\Chrome\Application\chrome.exe，就将C:\Program Files\Google\Chrome\Application配置到系统环境变量中。（如果不会配置系统环境变量，百度一下）

--------------------------------------------------------------------------------------------------------------------
3、这个不是错误，还是说一下：
使用命令：python -m weread_exporter -b $book_id -o epub -o pdf ，脚本采集书籍到一半的时候（免费阅读章节完的时候）会中断让你扫码登录，不是很方便。因此建议使用命令：python -m weread_exporter -b $book_id -o epub -o pdf --force-login True，该命令直接在最开始就让你登陆，避免采集到一半暂停。

**Comment by Bojack1127** [comment]
> **先说结论给大家打打气：该项目可以爬取微信读书上已购买的书籍，付费书籍需要购买才能完整爬取。**
> 
> ### 项目使用过程中遇到的两个问题：
> 1、运行**python -m weread_exporter -b $book_id -o epub -o pdf**命令时报错，报错提示如下： 报错： OSError: no library called "cairo-2" was found no library called "cairo" was found no library called "libcairo-2" was found cannot load library 'libcairo.so.2': error 0x7e cannot load library 'libcairo.2.dylib': error 0x7e cannot load library 'libcairo-2.dll': error 0x7e
> 
> **报错原因**：Python环境缺少这三个库：cairo-2、cairo、libcairo-2。如果使用以下命令直接安装这三个库还是会报错： pip install pycairo pip install cairocffi pip install WeasyPrint 因为在Windows系统上安装WeasyPrint还需要其它步骤，而且我们只需要安装WeasyPrint，其它两个库在安装WeasyPrint的过程中会自动附带。
> 
> **报错1的解决办法：** 在Windows 10环境中安装WeasyPrint可以按照以下步骤进行：
> 
> ①安装3.7版本以上的Python环境：访问Python官网（[https://www.python.org/downloads/windows/），下载并安装3.7版本以上的Python。（具体怎么安装网上找教程）
> 
> ②安装GTK+运行时环境：WeasyPrint使用了GTK+和cairo库来实现渲染和布局，因此需要先安装GTK+运行时环境。访问GTK+官网（[https://www.gtk.org/docs/installations/windows/）或者github项目（https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases），下载并安装最新版本的GTK+运行时环境。
> 
> ③安装WeasyPrint：在安装好Python和GTK+运行时环境后，可以使用以下命令来安装WeasyPrint（如果之前安装过就不用安装了）：
> 
> python -m pip install weasyprint
> 
> ④测试安装是否成功：在安装完WeasyPrint后，可以使用以下命令来测试是否安装成功：
> 
> python -m weasyprint --version 如果安装成功，将输出WeasyPrint的版本号。
> 
> 注意事项：
> 
> 如果你在安装WeasyPrint时遇到了找不到libffi-7.dll的错误，请下载libffi-7.dll文件并将其放置在Python安装目录下的DLLs文件夹中。
> 
> WeasyPrint需要的是GTK+ 3.x版本，而不是GTK+ 2.x版本。因此，请确保安装的是GTK+ 3.x版本的运行时环境。 不确定以上步骤是否对Windows 11适用，Windows 11系统安装WeasyPrint，可以参考官网的windows部分（[https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#cairo）](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#cairo%EF%BC%89)
> 
> 2、安装完WeasyPrint后，执行命令**python -m weread_exporter -b $book_id -o epub -o pdf**报错： Windows 10系统中提示文件找不到（FileNotFound）。mac系统中提示chrome找不到。
> 
> 报错原因：没有配置Chrome浏览器的系统环境变量。
> 
> 解决办法：将chrome.exe的目录配置在系统环境变量中。比如，我的谷歌浏览器路径是：C:\Program Files\Google\Chrome\Application\chrome.exe，就将C:\Program Files\Google\Chrome\Application配置到系统环境变量中。（如果不会配置系统环境变量，百度一下）
> 
> 3、这个不是错误，还是说一下： 使用命令：python -m weread_exporter -b $book_id -o epub -o pdf ，脚本采集书籍到一半的时候（免费阅读章节完的时候）会中断让你扫码登录，不是很方便。因此建议使用命令：python -m weread_exporter -b $book_id -o epub -o pdf --force-login，该命令直接在最开始就让你登陆，避免采集到一半暂停。
> 
> 备注：使用的时候遇到一个问题：如果之前使用这个项目的脚本登录过微信读书（就是运行脚本，脚本会自动调用Chrome打开微信读书的网页，你在这个网页登录过），那么之后就不能使用python -m weread_exporter -b $book_id -o epub -o pdf --force-login，否则会报错。这时候直接用python -m weread_exporter -b $book_id -o epub -o pdf 就好了。

十分感谢你的帮助，这些都设置好了，但是运行代码后扫码登录后，一小会就自动关了窗口，该怎么弄啊（win10+python3.9）？
D:\weread-exporter>python -m weread_exporter -b 08232ac0720befa90825d88 -o epub -o pdf
[2023-05-11 13:56:23,565][INFO]Exporting book 08232ac0720befa90825d88
[2023-05-11 13:56:23,941][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/08232ac0720befa90825d88
[2023-05-11 13:56:24,505][INFO]Browser listening on: ws://127.0.0.1:52744/devtools/browser/1cbe3df2-9107-4d13-9587-b14fd21ceebf
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\weread-exporter\weread_exporter\__main__.py", line 126, in <module>
    main()
  File "D:\weread-exporter\weread_exporter\__main__.py", line 122, in main
    loop.run_until_complete(async_main())
  File "D:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\weread-exporter\weread_exporter\__main__.py", line 63, in async_main
    await page.launch(args.force_login)
  File "D:\weread-exporter\weread_exporter\webpage.py", line 170, in launch
    await self._page.waitForSelector("div.readerFooter a")
  File "D:\Program Files\Python39\Lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "div.readerFooter a" failed: timeout 30000ms exceeds.
[2023-05-11 13:56:57,102][INFO]terminate chrome process...

**Comment by jiao-long** [comment]
不能用了，大家都退了吧

**Comment by brokench** [comment]
"python -m pip install weasyprint"
请问这个命令是在哪里输入并且运行呀？

**Comment by hal9000123** [comment]
你好，请问一下，为什么我按照步骤，下载gtk3配好环境变量，到测试WeasyPrint是否安装成功那步，还是会报错：
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by f0ghua** [comment]
看看你的 python 是不是 64 位的，和 gtk3 的位数是不是匹配
