### ISSUE TITLE
抓取书时遇到UnicodeEncodeError

### ISSUE THREAD

**Issue by damoguyanzero** [drunkdream/weread-exporter#14]
在抓取63f32a40813ab7cd5g011236这本书的第二章时，会遇到报错：UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 7: illegal multibyte sequence。

**Comment by drunkdream** [comment]
麻烦发下完整的报错堆栈

**Comment by damoguyanzero** [comment]
D:\Software\weread-exporter-main-2>python -m weread_exporter -b 63f32a40813ab7cd5g011236 -o epub
[2023-05-15 17:06:08,594][INFO]Exporting book 63f32a40813ab7cd5g011236
[2023-05-15 17:06:08,750][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/63f32a40813ab7cd5g011236
[2023-05-15 17:06:09,351][INFO]Browser listening on: ws://127.0.0.1:53512/devtools/browser/558eecf5-5b23-4ca7-acea-a86ac9cfac41
[2023-05-15 17:06:11,194][INFO][WeReadExporter] Check chapter 2/版权信息
[2023-05-15 17:06:11,194][INFO][WeReadExporter] File cache\63f32a40813ab7cd5g011236\chapters\1-2.md not exist
[2023-05-15 17:06:11,195][INFO][WeReadWebPage] Go to chapter 2
[2023-05-15 17:06:11,206][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/63f32a40813ab7cd5g011236kc81322c012c81e728d9d180
[2023-05-15 17:06:11,345][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 17:06:11,347][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 17:06:11,348][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 17:06:14,551][INFO][WeReadExporter] Export chapter 版权信息 to cache\63f32a40813ab7cd5g011236\chapters\1-2.md
[2023-05-15 17:06:21,205][INFO][WeReadExporter] Check chapter 3/地图
[2023-05-15 17:06:21,205][INFO][WeReadExporter] File cache\63f32a40813ab7cd5g011236\chapters\2-3.md not exist
[2023-05-15 17:06:21,205][INFO][WeReadWebPage] Go to chapter 3
[2023-05-15 17:06:21,211][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/63f32a40813ab7cd5g011236kecc32f3013eccbc87e4b62e
[2023-05-15 17:06:21,325][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 17:06:21,327][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 17:06:21,328][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 17:06:24,385][INFO][WeReadExporter] Export chapter 地图 to cache\63f32a40813ab7cd5g011236\chapters\2-3.md
[2023-05-15 17:06:31,219][INFO][WeReadExporter] Check chapter 4/出场人物
[2023-05-15 17:06:31,219][INFO][WeReadExporter] File cache\63f32a40813ab7cd5g011236\chapters\3-4.md not exist
[2023-05-15 17:06:31,219][INFO][WeReadWebPage] Go to chapter 4
[2023-05-15 17:06:31,226][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/63f32a40813ab7cd5g011236ka87322c014a87ff679a21ea
[2023-05-15 17:06:31,326][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 17:06:31,327][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 17:06:31,328][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 17:06:34,690][INFO][WeReadExporter] Export chapter 出场人物 to cache\63f32a40813ab7cd5g011236\chapters\3-4.md
[2023-05-15 17:06:41,227][INFO][WeReadExporter] Check chapter 5/霍拉大师写下的序文
[2023-05-15 17:06:41,227][INFO][WeReadExporter] File cache\63f32a40813ab7cd5g011236\chapters\4-5.md not exist
[2023-05-15 17:06:41,227][INFO][WeReadWebPage] Go to chapter 5
[2023-05-15 17:06:41,233][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/63f32a40813ab7cd5g011236ke4d32d5015e4da3b7fbb1fa
[2023-05-15 17:06:41,371][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 17:06:41,372][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 17:06:41,373][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 17:06:46,294][INFO][WeReadExporter] Export chapter 霍拉大师写下的序文 to cache\63f32a40813ab7cd5g011236\chapters\4-5.md
[2023-05-15 17:06:51,241][INFO][WeReadExporter] Check chapter 6/序幕 在船上
[2023-05-15 17:06:51,241][INFO][WeReadExporter] File cache\63f32a40813ab7cd5g011236\chapters\5-6.md not exist
[2023-05-15 17:06:51,241][INFO][WeReadWebPage] Go to chapter 6
[2023-05-15 17:06:51,249][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/63f32a40813ab7cd5g011236k16732dc0161679091c5aeb1
[2023-05-15 17:06:51,378][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 17:06:51,380][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 17:06:51,381][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 17:06:59,646][INFO][WeReadExporter] Export chapter 序幕 在船上 to cache\63f32a40813ab7cd5g011236\chapters\5-6.md
Traceback (most recent call last):
  File "C:\Users\huyuj\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\huyuj\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Software\weread-exporter-main-2\weread_exporter\__main__.py", line 126, in <module>
    main()
  File "D:\Software\weread-exporter-main-2\weread_exporter\__main__.py", line 122, in main
    loop.run_until_complete(async_main())
  File "C:\Users\huyuj\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Software\weread-exporter-main-2\weread_exporter\__main__.py", line 69, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "D:\Software\weread-exporter-main-2\weread_exporter\export.py", line 318, in export_markdown
    fp.write(markdown)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 7: illegal multibyte sequence
[2023-05-15 17:06:59,678][INFO]terminate chrome process...

**Comment by drunkdream** [comment]
Fix by #19

**Comment by damoguyanzero** [comment]
已解决，多谢！
