### ISSUE TITLE
请问能看下这个问题吗，感谢。

### ISSUE THREAD

**Issue by Bojack1127** [drunkdream/weread-exporter#15]
运行代码后扫码登录后，一小会就自动关了窗口，该怎么弄啊？（win10+python3.9 chrome113/114都试过）
```
D:\weread-exporter>python -m weread_exporter -b 08232ac0720befa90825d88 -o epub -o pdf
[2023-05-11 13:56:23,565][INFO]Exporting book 08232ac0720befa90825d88
[2023-05-11 13:56:23,941][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/08232ac0720befa90825d88
[2023-05-11 13:56:24,505][INFO]Browser listening on: ws://127.0.0.1:52744/devtools/browser/1cbe3df2-9107-4d13-9587-b14fd21ceebf
Traceback (most recent call last):
File "D:\Program Files\Python39\lib\runpy.py", line 197, in run_module_as_main
return run_code(code, main_globals, None,
File "D:\Program Files\Python39\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "D:\weread-exporter\weread_exporter_main.py", line 126, in
main()
File "D:\weread-exporter\weread_exporter_main.py", line 122, in main
loop.run_until_complete(async_main())
File "D:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
return future.result()
File "D:\weread-exporter\weread_exporter_main.py", line 63, in async_main
await page.launch(args.force_login)
File "D:\weread-exporter\weread_exporter\webpage.py", line 170, in launch
await self._page.waitForSelector("div.readerFooter a")
File "D:\Program Files\Python39\Lib\site-packages\pyppeteer\frame_manager.py", line 855, in await
raise result
pyppeteer.errors.TimeoutError: Waiting for selector "div.readerFooter a" failed: timeout 30000ms exceeds.
[2023-05-11 13:56:57,102][INFO]terminate chrome process...
```

**Comment by drunkdream** [comment]
能给退出前页面的截图吗？

**Comment by Bojack1127** [comment]
抱歉看到的晚
调用chrome后 比例是因为调整过屏幕缩放导致 也试过恢复默认但仍是一样的
![Snipaste_2023-05-12_00-10-30](https://github.com/drunkdream/weread-exporter/assets/74670995/a370f836-40e9-4d00-a133-b53424cba32f)

![Snipaste_2023-05-12_00-10-52](https://github.com/drunkdream/weread-exporter/assets/74670995/f964ee94-5d8f-472b-b054-3103958be5bf)

**Comment by drunkdream** [comment]
这个是因为页面元素变化导致的，已经做了处理，更新代码后再看下是否正常

**Comment by Bojack1127** [comment]
谢谢作者，刚刚试了下以上的问题已解决。 但要登录才能看的出现以下报错，好像也是元素问题，但不知道怎么改。
```
PS D:\weread-exporter> python -m weread_exporter -b 19032aa07296151d1905099 -o epub -o pdf --force-login

(process:11852): GLib-GIO-WARNING **: 01:43:18.060: Failed to open application manifest `C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe\AppxManifest.xml' for package #32 (`Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.1023.0_neutral_neutral_8wekyb3d8bbwe'): error code 0x2
[2023-05-15 01:43:18,138][INFO]Exporting book 19032aa07296151d1905099
[2023-05-15 01:43:18,809][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/19032aa07296151d1905099
[2023-05-15 01:43:19,445][INFO]Browser listening on: ws://127.0.0.1:61034/devtools/browser/9166cd82-d6d9-498f-8041-f9e62fb35908
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\weread-exporter\weread_exporter\__main__.py", line 126, in <module>
    main()
  File "D:\weread-exporter\weread_exporter\__main__.py", line 122, in main
    loop.run_until_complete(async_main())
  File "D:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\weread-exporter\weread_exporter\__main__.py", line 63, in async_main
    await page.launch(args.force_login)
  File "D:\weread-exporter\weread_exporter\webpage.py", line 172, in launch
    await self.check_login()
AttributeError: 'WeReadWebPage' object has no attribute 'check_login'
[2023-05-15 01:43:23,296][INFO]terminate chrome process...
```

**Comment by drunkdream** [comment]
这个是因为`check_login`函数改成了`login`，调用的时候没有更新导致的，已修复

**Comment by Bojack1127** [comment]
已可正常运行，以下应该是windows下存在的最后一个问题了(字符类型不对报错后 尝试重复运行可继续运行直至导出 不确定是否自动跳过了报错的部分)：
检索后猜测应该可以用此方法解决，请作者看看是否有参考意义[](https://blog.csdn.net/China_AT001/article/details/115058459#:~:text=%E5%8F%AF%E9%80%9A%E8%BF%87chardet%E5%BA%93%E8%8E%B7%E5%8F%96%E5%88%B0%E6%96%87%E4%BB%B6%E7%9A%84%E7%BC%96%E7%A0%81%EF%BC%8C%E9%80%9A%E8%BF%87%E6%BA%90%E6%96%87%E4%BB%B6%E7%9A%84%E7%BC%96%E7%A0%81%E8%AF%BB%E5%8F%96%E4%B8%8D%E5%AE%B9%E6%98%93%E5%87%BA%E9%94%99)
`UnicodeEncodeError: 'gbk' codec can't encode character '\xd6' in position 465: illegal multibyte sequence`

**Comment by drunkdream** [comment]
这个最好发下堆栈，以方便我定位问题

**Comment by Bojack1127** [comment]
随机找了一本书下载
`D:\SoftwareCollection\Ebook tools\weread-exporter>python -m weread_exporter -b 32332e30813ab7c38g018044 -o epub -o pdf
[2023-05-15 21:17:54,517][INFO]Exporting book 32332e30813ab7c38g018044

(process:13868): GLib-GIO-WARNING **: 21:17:54.572: Failed to open application manifest `C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe\AppxManifest.xml' for package #32 (`Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.1023.0_neutral_neutral_8wekyb3d8bbwe'): error code 0x2
[2023-05-15 21:17:55,112][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/32332e30813ab7c38g018044
[2023-05-15 21:17:55,650][INFO]Browser listening on: ws://127.0.0.1:62665/devtools/browser/d0c8f09b-73b4-422b-bd8e-6481729bb2e8
[2023-05-15 21:17:55,959][INFO][WeReadWebPage] Current login user is Refresh
[2023-05-15 21:17:55,959][INFO][WeReadWebPage] Inject cookie wr_gender=0
[2023-05-15 21:17:55,975][INFO][WeReadWebPage] Inject cookie wr_avatar=https%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fvi_32%2FpeEI2sHrjnmTUEg0O12b3plU6wRCXZ0bicLMcRBx8mlg7YFQzo2cVF5UCsnmbQaDNCowksHZejT0p2ExHXXSJqQ%2F132
[2023-05-15 21:17:55,977][INFO][WeReadWebPage] Inject cookie wr_name=Refresh
[2023-05-15 21:17:55,979][INFO][WeReadWebPage] Inject cookie wr_rt=web%4087o5cN7C7ABPT1A1oCo_AL
[2023-05-15 21:17:55,980][INFO][WeReadWebPage] Inject cookie wr_skey=qP4sYUNY
[2023-05-15 21:17:55,982][INFO][WeReadWebPage] Inject cookie wr_vid=535604809
[2023-05-15 21:17:55,984][INFO][WeReadWebPage] Inject cookie wr_fp=3193575357
[2023-05-15 21:17:55,985][INFO][WeReadWebPage] Inject cookie wr_pf=0
[2023-05-15 21:17:55,986][INFO][WeReadWebPage] Inject cookie wr_localvid=c6032b8081fecae49c60532
[2023-05-15 21:17:55,988][INFO][WeReadWebPage] Inject cookie wr_gid=232136063
[2023-05-15 21:18:04,358][INFO][WeReadExporter] Check chapter 2/版权信息
[2023-05-15 21:18:04,359][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\1-2.md not exist
[2023-05-15 21:18:04,359][INFO][WeReadWebPage] Go to chapter 2
[2023-05-15 21:18:04,377][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044kc81322c012c81e728d9d180
[2023-05-15 21:18:04,966][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:18:04,967][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:18:04,968][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:18:08,851][INFO][WeReadExporter] Export chapter 版权信息 to cache\32332e30813ab7c38g018044\chapters\1-2.md
[2023-05-15 21:18:14,368][INFO][WeReadExporter] Check chapter 3/炁體源流（上册）
[2023-05-15 21:18:14,368][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\2-3.md not exist
[2023-05-15 21:18:14,368][INFO][WeReadWebPage] Go to chapter 3
[2023-05-15 21:18:14,383][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044kecc32f3013eccbc87e4b62e
[2023-05-15 21:18:15,008][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:18:15,010][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:18:15,011][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:18:18,448][INFO][WeReadExporter] Export chapter 炁體源流（上册） to cache\32332e30813ab7c38g018044\chapters\2-3.md
[2023-05-15 21:18:24,364][INFO][WeReadExporter] Check chapter 4/版权信息
[2023-05-15 21:18:24,365][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\3-4.md not exist
[2023-05-15 21:18:24,368][INFO][WeReadWebPage] Go to chapter 4
[2023-05-15 21:18:24,377][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044ka87322c014a87ff679a21ea
[2023-05-15 21:18:25,007][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:18:25,008][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:18:25,010][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:18:28,531][INFO][WeReadExporter] Export chapter 版权信息 to cache\32332e30813ab7c38g018044\chapters\3-4.md
[2023-05-15 21:18:34,372][INFO][WeReadExporter] Check chapter 5/插图
[2023-05-15 21:18:34,372][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\4-5.md not exist
[2023-05-15 21:18:34,372][INFO][WeReadWebPage] Go to chapter 5
[2023-05-15 21:18:34,387][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044ke4d32d5015e4da3b7fbb1fa
[2023-05-15 21:18:35,045][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:18:35,047][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:18:35,048][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:18:39,072][INFO][WeReadExporter] Export chapter 插图 to cache\32332e30813ab7c38g018044\chapters\4-5.md
[2023-05-15 21:18:44,378][INFO][WeReadExporter] Check chapter 6/自序
[2023-05-15 21:18:44,379][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\5-6.md not exist
[2023-05-15 21:18:44,381][INFO][WeReadWebPage] Go to chapter 6
[2023-05-15 21:18:44,388][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044k16732dc0161679091c5aeb1
[2023-05-15 21:18:45,066][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:18:45,072][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:18:45,073][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:18:48,671][INFO][WeReadExporter] Export chapter 自序 to cache\32332e30813ab7c38g018044\chapters\5-6.md
[2023-05-15 21:18:54,402][INFO][WeReadExporter] Check chapter 7/再版序
[2023-05-15 21:18:54,403][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\6-7.md not exist
[2023-05-15 21:18:54,406][INFO][WeReadWebPage] Go to chapter 7
[2023-05-15 21:18:54,415][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044k8f132430178f14e45fce0f7
[2023-05-15 21:18:55,240][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:18:55,241][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:18:55,242][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:18:58,931][INFO][WeReadExporter] Export chapter 再版序 to cache\32332e30813ab7c38g018044\chapters\6-7.md
[2023-05-15 21:19:04,430][INFO][WeReadExporter] Check chapter 8/太清元道真經註解
[2023-05-15 21:19:04,430][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\7-8.md not exist
[2023-05-15 21:19:04,436][INFO][WeReadWebPage] Go to chapter 8
[2023-05-15 21:19:04,442][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044kc9f326d018c9f0f895fb5e4
[2023-05-15 21:19:05,095][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:19:05,096][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:19:05,100][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:19:10,515][INFO][WeReadExporter] Export chapter 太清元道真經註解 to cache\32332e30813ab7c38g018044\chapters\7-8.md
[2023-05-15 21:19:14,446][INFO][WeReadExporter] Check chapter 9/太上老君説常清静經註
[2023-05-15 21:19:14,446][INFO][WeReadExporter] File cache\32332e30813ab7c38g018044\chapters\8-9.md not exist
[2023-05-15 21:19:14,446][INFO][WeReadWebPage] Go to chapter 9
[2023-05-15 21:19:14,461][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/32332e30813ab7c38g018044k45c322601945c48cce2e120
[2023-05-15 21:19:15,149][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-15 21:19:15,150][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-15 21:19:15,152][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.5bafd699.js
[2023-05-15 21:19:23,231][INFO][WeReadWebPage] Go to next page
[2023-05-15 21:19:23,941][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_044-1.jpg
[2023-05-15 21:19:23,942][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_046-1.jpg
[2023-05-15 21:19:23,945][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_048-s1.png
[2023-05-15 21:19:23,947][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_048-1.jpg
[2023-05-15 21:19:23,948][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_051-1.jpg
[2023-05-15 21:19:23,949][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_053-1.jpg
[2023-05-15 21:19:23,949][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_056-1.jpg
[2023-05-15 21:19:23,951][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_058-1.jpg
[2023-05-15 21:19:23,951][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_059-s1.png
[2023-05-15 21:19:23,953][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_061-1.jpg
[2023-05-15 21:19:23,954][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_063-1.jpg
[2023-05-15 21:19:23,955][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_066-1.jpg
[2023-05-15 21:19:23,956][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_068-1.jpg
[2023-05-15 21:19:29,362][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_071-1.jpg
[2023-05-15 21:19:29,362][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_073-1.jpg
[2023-05-15 21:19:29,367][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_076-1.jpg
[2023-05-15 21:19:29,368][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_076-s1.png
[2023-05-15 21:19:29,369][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_078-1.jpg
[2023-05-15 21:19:29,370][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_081-1.jpg
[2023-05-15 21:19:29,372][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_083-1.jpg
[2023-05-15 21:19:29,373][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_086-1.jpg
[2023-05-15 21:19:29,373][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_088-1.jpg
[2023-05-15 21:19:29,374][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_091-1.jpg
[2023-05-15 21:19:29,375][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_093-1.jpg
[2023-05-15 21:19:29,377][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_096-1.jpg
[2023-05-15 21:19:29,380][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_099-1.jpg
[2023-05-15 21:19:30,399][INFO][WeReadWebPage] Go to next page
[2023-05-15 21:19:31,261][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_101-1.jpg
[2023-05-15 21:19:31,261][INFO][WeReadWebPage] Fetch url https://res.weread.qq.com/wrepub/CB_3300055608_103-s1.png
[2023-05-15 21:19:32,296][INFO][WeReadExporter] Export chapter 太上老君説常清静經註 to cache\32332e30813ab7c38g018044\chapters\8-9.md
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\SoftwareCollection\Ebook tools\weread-exporter\weread_exporter\__main__.py", line 126, in <module>
    main()
  File "D:\SoftwareCollection\Ebook tools\weread-exporter\weread_exporter\__main__.py", line 122, in main
    loop.run_until_complete(async_main())
  File "D:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\SoftwareCollection\Ebook tools\weread-exporter\weread_exporter\__main__.py", line 69, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "D:\SoftwareCollection\Ebook tools\weread-exporter\weread_exporter\export.py", line 318, in export_markdown
    fp.write(markdown)
UnicodeEncodeError: 'gbk' codec can't encode character '\u361e' in position 7068: illegal multibyte sequence
[2023-05-15 21:19:32,321][INFO]terminate chrome process...`

**Comment by drunkdream** [comment]
Fix with #19 
> 最好把上面贴出来的日志中的cookie删掉，不然会有安全风险

**Comment by Bojack1127** [comment]
感谢！
