### ISSUE TITLE
报错，更新后无法运行

### ISSUE THREAD

**Issue by lj1998008** [drunkdream/weread-exporter#25]
最新的，无法运行，卡住了，不自动阅读和翻页，跳出一个浏览器卡住不动，接着又跳出一个浏览器，又卡住不动，接着又跳出一个浏览器，无限循环，卡住不自动阅读和翻页

C:\Users\2020\Desktop\1\wxds\***-exporter-main>python -m ***_exporter -b 7e432620813ab7a02g010361 -o epub
[2023-05-21 08:54:00,360][INFO]Exporting book 7e432620813ab7a02g010361
[2023-05-21 08:54:00,652][INFO][***WebPage] Launch url https://***.qq.com/web/bookDetail/7e432620813ab7a02g010361
[2023-05-21 08:54:01,176][INFO]Browser listening on: ws://127.0.0.1:4013/devtools/browser/9dbe8654-907d-42f0-9213-1ffe0908227b
[2023-05-21 08:54:01,407][INFO][***WebPage] Current login user is ***用户
[2023-05-21 08:54:01,407][INFO][***WebPage] Inject cookie wr_gender=0
[2023-05-21 08:54:01,410][INFO][***WebPage] Inject cookie w*
[2023-05-21 08:54:01,411][INFO][***WebPage] Inject cookie *
***
[2023-05-21 08:54:33,204][ERROR]Launch book 7e432620813ab7a02g010361 home page failed
Traceback (most recent call last):
  File "C:\Users\2020\Desktop\1\wxds\***-exporter-main\***_exporter\__main__.py", line 69, in async_main
    await page.launch(args.force_login)
  File "C:\Users\2020\Desktop\1\wxds\***-exporter-main\***_exporter\webpage.py", line 194, in launch
    await self.wait_for_avatar()
  File "C:\Users\2020\Desktop\1\wxds\***-exporter-main\***_exporter\webpage.py", line 241, in wait_for_avatar
    raise RuntimeError("Wait for avatar timeout")
RuntimeError: Wait for avatar timeout
[2023-05-21 08:54:33,206][INFO][***WebPage] Launch url https://***.qq.com/web/bookDetail/7e432620813ab7a02g010361
[2023-05-21 08:54:33,728][INFO]Browser listening on: ws://127.0.0.1:4062/devtools/browser/0aabc112-dbe1-4bc7-8e45-3a51f88e0ecc
[2023-05-21 08:54:33,935][INFO][***WebPage] Current login user is ***用户
[2023-05-21 08:54:33,936][INFO][***WebPage] Inject cookie *
****
[2023-05-21 08:54:37,609][INFO]connection closed
[2023-05-21 08:55:10,922][ERROR]Launch book 7e432620813ab7a02g010361 home page failed
Traceback (most recent call last):
  File "C:\Users\2020\Desktop\1\wxds\***-exporter-main\***_exporter\__main__.py", line 69, in async_main
    await page.launch(args.force_login)
  File "C:\Users\2020\Desktop\1\wxds\***-exporter-main\***_exporter\webpage.py", line 194, in launch
    await self.wait_for_avatar()
  File "C:\Users\2020\Desktop\1\wxds\***-exporter-main\***_exporter\webpage.py", line 241, in wait_for_avatar
    raise RuntimeError("Wait for avatar timeout")
RuntimeError: Wait for avatar timeout
[2023-05-21 08:55:10,923][INFO][***WebPage] Launch url https://***.qq.com/web/bookDetail/7e432620813ab7a02g010361
[2023-05-21 08:55:11,446][INFO]Browser listening on: ws://127.0.0.1:4126/devtools/browser/867b0443-af8f-44b5-9e2a-f4e8918b82e1
[2023-05-21 08:55:11,688][INFO][***WebPage] Current login user is ***用户
[2023-05-21 08:55:11,688][INFO][***WebPage] Inject cookie wr_gender=0

[2023-05-21 08:55:17,905][INFO]connection closed

**Comment by drunkdream** [comment]
https://github.com/drunkdream/weread-exporter/blob/main/weread_exporter/webpage.py#L231

试下把这里的超时时间改成`60`或者更长试下呢，并确认下报错的时候页面上的头像图标是否展示出来了呢

**Comment by lj1998008** [comment]
可以了，前面报错的时候登录后的头像没显示出来，现在头像显示出来了

**Comment by lj1998008** [comment]
有时会遇到运行后跳出来来无数个浏览器

**Comment by lj1998008** [comment]
7e432620813ab7a02g010361
这个完成后少了最后3个知识点的内容

90b32020813ab7914g019ab7
这个运行到第三篇的时候，卡住不动了
[2023-05-19 14:31:37,263][ERROR][Exporter] Go to chapter 第三篇 **** failed
Traceback (most recent call last):
File "C:\Users\2020\Desktop\1*-exporter-main*_exporter\export.py", line 303, in export_markdown
await self._page.goto_chapter(
File "C:\Users\2020\Desktop\1*-exporter-main**_exporter\webpage.py", line 390, in goto_chapter
await self._page.goto(self._url, timeout=1000 * timeout)
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\page.py", line 837, in goto
raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
[2023-05-19 14:31:37,266][INFO][***WebPage] Go to chapter 13
[2023-05-19 14:31:37,267][ERROR]connection unexpectedly closed
[2023-05-19 14:31:37,268][ERROR]Task exception was never retrieved
future: <Task finished name='Task-2264' coro=<Connection._async_send() done, defined at C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 968, in transfer_data
message = await self.read_message()
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1038, in read_message
frame = await self.read_data_frame(max_size=self.max_size)
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1113, in read_data_frame
frame = await self.read_frame(max_size)
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1170, in read_frame
frame = await Frame.read(
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\framing.py", line 69, in read
data = await reader(2)
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 706, in readexactly
raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
await self.connection.send(msg)
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
await self.ensure_open()
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
await self.dispose()
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
await self._on_close()
File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state

卡住了

**Comment by drunkdream** [comment]
试下通过`--load-timeout=300`参数来看下有没有效果

**Comment by lj1998008** [comment]
感谢！
试了好像还是卡住，不用管它了，太麻烦你了！

**Comment by lj1998008** [comment]
又试了几个，感觉卡的的页面往往会有图片，以前用过这个https://github.com/magicdawn/weread-spy，好像没卡过

**Comment by lj1998008** [comment]
报错，好像和以前一样的：
[2023-05-30 21:42:15,654][INFO][WeReadExporter] File cache\0e932260813ab7297g01583b\chapters\5-16.md not exist
[2023-05-30 21:42:15,654][INFO][WeReadWebPage] Go to chapter 16
[2023-05-30 21:42:15,662][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/0e932260813ab7297g01583bkc7432af0210c74d97b01b1c
[2023-05-30 21:42:15,976][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-05-30 21:42:15,977][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.f543b21b.css
[2023-05-30 21:42:15,979][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.fae54453.js
[2023-05-30 21:42:45,654][ERROR][WeReadExporter] Go to chapter 回忆二 海上土 failed
Traceback (most recent call last):
  File "C:\Users\2020\Desktop\1\we\weread-exporter-main\weread_exporter\export.py", line 312, in export_markdown
    await self._page.goto_chapter(
  File "C:\Users\2020\Desktop\1\we\weread-exporter-main\weread_exporter\webpage.py", line 390, in goto_chapter
    await self._page.goto(self._url, timeout=1000 * timeout)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
[2023-05-30 21:42:45,656][INFO][WeReadWebPage] Go to chapter 16
[2023-05-30 21:42:45,658][ERROR]connection unexpectedly closed
[2023-05-30 21:42:45,658][ERROR]Task exception was never retrieved
future: <Task finished name='Task-277' coro=<Connection._async_send() done, defined at C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
