### ISSUE TITLE
改为300还是超时

### ISSUE THREAD

**Issue by lidongRebirth** [drunkdream/weread-exporter#26]
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
[2023-06-12 17:15:10,147][INFO][WeReadWebPage] Go to chapter 5
[2023-06-12 17:15:10,148][ERROR]connection unexpectedly closed
[2023-06-12 17:15:10,148][ERROR]Task exception was never retrieved
future: <Task finished name='Task-618' coro=<Connection._async_send() done, defined at F:\python_install\Lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 1314, in close_connection
    await self.transfer_data_task
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state

**Comment by lidongRebirth** [comment]
登录后还是超时，发生在前言那里
[2023-06-12 17:32:57,265][INFO][WeReadWebPage] Inject cookie wr_gid=252366598
[2023-06-12 17:33:06,883][INFO][WeReadExporter] Check chapter 2/版权信息
[2023-06-12 17:33:06,883][INFO][WeReadExporter] Check chapter 3/作者简介
[2023-06-12 17:33:06,884][INFO][WeReadExporter] Check chapter 4/内容简介
[2023-06-12 17:33:06,885][INFO][WeReadExporter] Check chapter 5/前言
[2023-06-12 17:33:06,885][INFO][WeReadExporter] File cache\43e32a30813ab752ag01653b\chapters\4-5.md not exist
[2023-06-12 17:33:06,885][INFO][WeReadWebPage] Go to chapter 5
[2023-06-12 17:33:06,910][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/43e32a30813ab752ag01653bke4d32d5015e4da3b7fbb1fa
[2023-06-12 17:33:07,354][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-06-12 17:33:07,355][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.4605d864.css
[2023-06-12 17:33:07,356][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.344c0719.js
[2023-06-12 17:33:36,901][ERROR][WeReadExporter] Go to chapter 前言 failed
Traceback (most recent call last):
  File "I:\Python\weread_exporter\export.py", line 312, in export_markdown
    await self._page.goto_chapter(
  File "I:\Python\weread_exporter\webpage.py", line 390, in goto_chapter
    await self._page.goto(self._url, timeout=1000 * timeout)
  File "F:\python_install\Lib\site-packages\pyppeteer\page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
[2023-06-12 17:33:36,902][INFO][WeReadWebPage] Go to chapter 5
[2023-06-12 17:33:36,903][ERROR]connection unexpectedly closed
[2023-06-12 17:33:36,905][ERROR]Task exception was never retrieved
future: <Task finished name='Task-1049' coro=<Connection._async_send() done, defined at F:\python_install\Lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 1314, in close_connection
    await self.transfer_data_task
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "F:\python_install\Lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "F:\python_install\Lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state

**Comment by drunkdream** [comment]
看日志超时时间还是30秒，你是怎么改的？

**Comment by 58000** [comment]
如何改300

**Comment by lidongRebirth** [comment]
我在这里将超时时间30改为了300 async def wait_for_avatar(self, timeout=300):，但还是不行，不清楚为啥提示还是Navigation Timeout Exceeded: 30000 ms exceeded.

**Comment by lidongRebirth** [comment]
> 看日志超时时间还是30秒，你是怎么改的？

我在这里将超时时间30改为了300 async def wait_for_avatar(self, timeout=300):，但还是不行，不清楚为啥提示还是Navigation Timeout Exceeded: 30000 ms exceeded.
