### ISSUE TITLE
这个卡住不动了

### ISSUE THREAD

**Issue by lj1998008** [drunkdream/weread-exporter#28]
c2332c70813ab7157g011108
这个卡住不动了：
[2023-06-17 21:44:20,357][INFO][***Exporter] Check chapter 7/第1***
[2023-06-17 21:44:20,357][INFO][***Exporter] File cache\c2332c70813ab7157g011108\chapters\6-7.md not exist
[2023-06-17 21:44:20,357][INFO][***WebPage] Go to chapter 7
[2023-06-17 21:44:20,367][INFO][***WebPage] Fetch url https://***.***.com/web/reader/c2332c70813ab7157g011108k8f132430178f14e45fce0f7
[2023-06-17 21:44:20,730][INFO][***WebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-06-17 21:44:20,731][INFO][***WebPage] Fetch url https://***-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.4605d864.css
[2023-06-17 21:44:20,733][INFO][***WebPage] Fetch url https://***-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.d42bbcf6.js
[2023-06-17 21:44:24,030][INFO][***WebPage] Go to next page【卡住不动了】

**Comment by drunkdream** [comment]
必现吗？按Ctrl +C退出时能看到卡住的堆栈吗

**Comment by lj1998008** [comment]
> 必现吗？按Ctrl +C退出时能看到卡住的堆栈吗

嗯，每次都卡住，今天测试报错如下：

[2023-06-20 18:55:32,680][INFO][***Exporter] Check chapter 7/第1章 
[2023-06-20 18:55:32,681][INFO][***Exporter] File cache\c2332c70813ab7157g011108\chapters\6-7.md not exist
[2023-06-20 18:55:32,681][INFO][***WebPage] Go to chapter 7
[2023-06-20 18:55:32,692][INFO][***WebPage] Fetch url https://***.***.com/web/reader/c2332c70813ab7157g011108k8f132430178f14e45fce0f7
[2023-06-20 18:55:33,016][INFO][***WebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-06-20 18:55:33,021][INFO][***WebPage] Fetch url https://***-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.4605d864.css
[2023-06-20 18:55:33,022][INFO][***WebPage] Fetch url https://***-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.d42bbcf6.js
[2023-06-20 18:56:02,693][ERROR][***Exporter] Go to chapter 第1章 failed
Traceback (most recent call last):
  File "C:\Users\2020\Desktop\1\we\***-exporter-main\***_exporter\export.py", line 312, in export_markdown
    await self._page.goto_chapter(
  File "C:\Users\2020\Desktop\1\we\***-exporter-main\***_exporter\webpage.py", line 390, in goto_chapter
    await self._page.goto(self._url, timeout=1000 * timeout)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
[2023-06-20 18:56:02,697][INFO][***WebPage] Go to chapter 7
[2023-06-20 18:56:02,697][ERROR]connection unexpectedly closed
[2023-06-20 18:56:02,698][ERROR]Task exception was never retrieved
future: <Task finished name='Task-279' coro=<Connection._async_send() done, defined at C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 968, in transfer_data
    message = await self.read_message()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 1170, in read_frame
    frame = await Frame.read(
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\framing.py", line 69, in read
    data = await reader(2)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 706, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
【卡住不动了】

**Comment by lj1998008** [comment]
另外1个也是一样卡住：卡住的遇到过好几个

[2023-06-20 19:09:58,392][INFO][***Exporter] Check chapter 11/第 2 
[2023-06-20 19:09:58,393][INFO][***Exporter] File cache\08232ac0720befa90825d88\chapters\10-11.md not exist
[2023-06-20 19:09:58,394][INFO][***WebPage] Go to chapter 11
[2023-06-20 19:09:58,402][INFO][***WebPage] Fetch url https://***.qq.com/web/reader/08232ac0720befa90825d88k65132ca01b6512bd43d90e3
[2023-06-20 19:09:58,692][INFO][***WebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-06-20 19:09:58,693][INFO][***WebPage] Fetch url https://***-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.4605d864.css
[2023-06-20 19:09:58,695][INFO][***WebPage] Fetch url https://***-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.d42bbcf6.js
[2023-06-20 19:10:28,392][ERROR][***Exporter] Go to chapter 第 2  failed
Traceback (most recent call last):
  File "C:\Users\2020\Desktop\1\we\***-exporter-main\***_exporter\export.py", line 312, in export_markdown
    await self._page.goto_chapter(
  File "C:\Users\2020\Desktop\1\we\***-exporter-main\***_exporter\webpage.py", line 390, in goto_chapter
    await self._page.goto(self._url, timeout=1000 * timeout)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
[2023-06-20 19:10:28,395][INFO][***WebPage] Go to chapter 11
[2023-06-20 19:10:28,397][ERROR]connection unexpectedly closed
[2023-06-20 19:10:28,398][ERROR]Task exception was never retrieved
future: <Task finished name='Task-1445' coro=<Connection._async_send() done, defined at C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state

**Comment by lj1998008** [comment]
另外如果注释也能有就好了，嘿嘿

**Comment by drunkdream** [comment]
> 

注释指的是什么

**Comment by lj1998008** [comment]
> 

有些名词不是有注释解释嘛，有的会有，有的就没，就是阅读的时候显示的【注】，点一下注释就看到了
