### ISSUE TITLE
打开运行就报错了，无法运行

### ISSUE THREAD

**Issue by lj1998008** [drunkdream/weread-exporter#36]
Traceback (most recent call last):
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\2020\Desktop\2\weread-exporter-main\weread_exporter\__main__.py", line 147, in <module>
    main()
  File "C:\Users\2020\Desktop\2\weread-exporter-main\weread_exporter\__main__.py", line 143, in main
    loop.run_until_complete(async_main())
  File "C:\Users\2020\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\2020\Desktop\2\weread-exporter-main\weread_exporter\__main__.py", line 16, in async_main
    from . import export, utils, webpage
  File "C:\Users\2020\Desktop\2\weread-exporter-main\weread_exporter\export.py", line 8, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'

**Comment by drunkdream** [comment]
pip install bs4
加了个依赖
