### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Corotata** [drunkdream/weread-exporter#40]
安装完所有内容后，执行

```
 python -m weread_exporter -b 6a032b60813ab71f0g01944f -o pdf --force-login
```
会报下面的错误，我搜了很多cannot load library 'libcairo.so.2'相关的答案，按照他们的方式也去尝试都没有效果，我也不确定是不是我本地环境有问题，新接触Python，很多东西不了解，特来咨询下大佬，提供下方向。
 
Traceback (most recent call last):
  File "/Applications/Xcode-14.1.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode-14.1.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/cat/Downloads/weread-exporter-main/weread_exporter/__main__.py", line 147, in <module>
    main()
  File "/Users/cat/Downloads/weread-exporter-main/weread_exporter/__main__.py", line 143, in main
    loop.run_until_complete(async_main())
  File "/Applications/Xcode-14.1.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cat/Downloads/weread-exporter-main/weread_exporter/__main__.py", line 16, in async_main
    from . import export, utils, webpage
  File "/Users/cat/Downloads/weread-exporter-main/weread_exporter/export.py", line 12, in <module>
    from weasyprint import HTML, CSS
  File "/Users/cat/Downloads/weread-exporter-main/venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/cat/Downloads/weread-exporter-main/venv/lib/python3.9/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/cat/Downloads/weread-exporter-main/venv/lib/python3.9/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/Users/cat/Downloads/weread-exporter-main/venv/lib/python3.9/site-packages/weasyprint/text.py", line 11, in <module>
    import cairocffi as cairo
  File "/Users/cat/Downloads/weread-exporter-main/venv/lib/python3.9/site-packages/cairocffi/__init__.py", line 47, in <module>
    cairo = dlopen(
  File "/Users/cat/Downloads/weread-exporter-main/venv/lib/python3.9/site-packages/cairocffi/__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: 'libcairo.so.2' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file, not in dyld cache), 'libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: 'libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: 'libcairo-2.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file, not in dyld cache), 'libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'

**Comment by drunkdream** [comment]
试下`brew install cairo`呢
