### ISSUE TITLE
这本书下载会报错

### ISSUE THREAD

**Issue by zsj1zsj** [drunkdream/weread-exporter#42]
hash： b5832a8072169a18b58c570
试了很多次都一样，其他书就没这个问题。

lynn@yongmingzhangs-MacBook-Pro weread-exporter-main % python -m weread_exporter -b b5832a8072169a18b58c570 -o epub
[2023-08-09 08:51:12,793][INFO]Exporting book b5832a8072169a18b58c570
[2023-08-09 08:51:12,920][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/b5832a8072169a18b58c570
[2023-08-09 08:51:14,039][INFO]Browser listening on: ws://127.0.0.1:53070/devtools/browser/1fd9307a-20fb-43f1-ade3-ad8899ffeab5
[2023-08-09 08:51:14,815][INFO][WeReadWebPage] Update cookie wr_vid=*****
[2023-08-09 08:51:14,815][INFO][WeReadWebPage] Update cookie wr_skey=*********
[2023-08-09 08:51:14,816][INFO][WeReadWebPage] Update cookie wr_pf=0
[2023-08-09 08:51:14,816][INFO][WeReadWebPage] Update cookie wr_rt=*******
[2023-08-09 08:51:14,910][INFO][WeReadWebPage] Current login user is ********
[2023-08-09 08:51:14,910][INFO][WeReadWebPage] Inject cookie wr_gender=1
[2023-08-09 08:51:14,914][INFO][WeReadWebPage] Inject cookie ***********************
[2023-08-09 08:51:14,915][INFO][WeReadWebPage] Inject cookie wr_name=****
[2023-08-09 08:51:14,917][INFO][WeReadWebPage] Inject cookie wr_rt=*********
[2023-08-09 08:51:14,918][INFO][WeReadWebPage] Inject cookie wr_skey=********
[2023-08-09 08:51:14,920][INFO][WeReadWebPage] Inject cookie wr_vid=******
[2023-08-09 08:51:14,921][INFO][WeReadWebPage] Inject cookie wr_fp=******
[2023-08-09 08:51:14,922][INFO][WeReadWebPage] Inject cookie wr_pf=0
[2023-08-09 08:51:14,924][INFO][WeReadWebPage] Inject cookie wr_localvid=******
[2023-08-09 08:51:14,925][INFO][WeReadWebPage] Inject cookie wr_gid=******
[2023-08-09 08:51:21,067][INFO][WeReadExporter] Check chapter 2/说明
[2023-08-09 08:51:21,067][INFO][WeReadExporter] File cache/b5832a8072169a18b58c570/chapters/1-2.md not exist
[2023-08-09 08:51:21,068][INFO][WeReadWebPage] Go to chapter 2
[2023-08-09 08:51:21,086][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/b5832a8072169a18b58c570kc81322c012c81e728d9d180
[2023-08-09 08:51:21,354][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2023-08-09 08:51:21,354][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.4605d864.css
[2023-08-09 08:51:21,355][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.c15c0d84.js
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/lynn/Downloads/weread-exporter-main/weread_exporter/__main__.py", line 147, in <module>
    main()
  File "/Users/lynn/Downloads/weread-exporter-main/weread_exporter/__main__.py", line 143, in main
    loop.run_until_complete(async_main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/lynn/Downloads/weread-exporter-main/weread_exporter/__main__.py", line 83, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "/Users/lynn/Downloads/weread-exporter-main/weread_exporter/export.py", line 353, in export_markdown
    markdown = await self._page.get_markdown()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lynn/Downloads/weread-exporter-main/weread_exporter/webpage.py", line 363, in get_markdown
    raise RuntimeError("Wait for creating markdown timeout")
RuntimeError: Wait for creating markdown timeout

**Comment by drunkdream** [comment]
麻烦发下当前目录下的日志文件，应该是：b5832a8072169a18b58c570.log

**Comment by zsj1zsj** [comment]
[b5832a8072169a18b58c570.log](https://github.com/drunkdream/weread-exporter/files/12345427/b5832a8072169a18b58c570.log)

**Comment by zsj1zsj** [comment]
> 麻烦发下当前目录下的日志文件，应该是：b5832a8072169a18b58c570.log

上面已提供

**Comment by champkeh** [comment]
试试这个呢？https://weread.deno.dev
