### ISSUE TITLE
makdown creating timeout

### ISSUE THREAD

**Issue by Algieba-dean** [drunkdream/weread-exporter#44]
环境配置没问题
运行环境 
内核版本 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux
python 版本  Python 3.11.4
chrome 版本 Google Chrome 116.0.5845.96 unknown

报错信息如下
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kali/python/weread-exporter/weread_exporter/__main__.py", line 147, in <module>
    main()
  File "/home/kali/python/weread-exporter/weread_exporter/__main__.py", line 143, in main
    loop.run_until_complete(async_main())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kali/python/weread-exporter/weread_exporter/__main__.py", line 83, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "/home/kali/python/weread-exporter/weread_exporter/export.py", line 353, in export_markdown
    markdown = await self._page.get_markdown()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/python/weread-exporter/weread_exporter/webpage.py", line 363, in get_markdown
    raise RuntimeError("Wait for creating markdown timeout")
RuntimeError: Wait for creating markdown timeout
[2023-08-16 22:18:33,692][INFO]terminate chrome process...`
运行行为 成功启动chrome，并开始采录第一页，几秒过后即报错

**Comment by zeng-zr** [comment]
我也遇到了这个问题。可以尝试在程序打开书本内容页之后，点击页面上“上一章”。如果来不及操作就把markdwon timeout时间调长一些。
