### ISSUE TITLE
是必须购买的书籍才可以导出吗？

### ISSUE THREAD

**Issue by HcoreYang** [drunkdream/weread-exporter#56]
会员到了付费内容部分就没法导出了？我发现我自己购买的书籍可以导出没问题，但是每购买的，就会卡在付费内容那里无限的重启，无法继续。

错误信息如下：
[2023-12-21 10:51:15,028][WARNING]Load chapter failed, close browser and retry
[2023-12-21 10:51:15,028][INFO]terminate chrome process...
[2023-12-21 10:51:15,029][ERROR]connection unexpectedly closed
[2023-12-21 10:51:15,029][ERROR]Task exception was never retrieved
future: <Task finished name='Task-551' coro=<Connection._async_send() done, defined at C:\Python312\Lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 1314, in close_connection
    await self.transfer_data_task
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\Python312\Lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\Python312\Lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state

**Comment by ffaffAHA** [comment]
我购买的书现在加载到了会员部分也不能导出来了。

**Comment by HcoreYang** [comment]
> 我购买的书现在加载到了会员部分也不能导出来了。

有解决的办法吗？

**Comment by drunkdream** [comment]
可以理解成手机上能看的部分都是可以导出的
