### ISSUE TITLE
您好，小白Mac遇到如下No module named 'bs4'问题，卡在这里了，谢谢帮忙！

### ISSUE THREAD

**Issue by JaimeISOK** [drunkdream/weread-exporter#60]
jaimezhang@192 weread-exporter-main % python -m weread_exporter -b 08232ac0720befa90825d88 -o epub -o pdf
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jaimezhang/weread-exporter-main/weread_exporter/__main__.py", line 158, in <module>
    main()
  File "/Users/jaimezhang/weread-exporter-main/weread_exporter/__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jaimezhang/weread-exporter-main/weread_exporter/__main__.py", line 17, in async_main
    from . import export, utils, webpage
  File "/Users/jaimezhang/weread-exporter-main/weread_exporter/export.py", line 8, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'

**Comment by brmysss** [comment]
我也遇到了这个问题

**Comment by LilacZhang** [comment]
python3 -m weread_exporter -b $book_id -o epub -o pdf

**Comment by drunkdream** [comment]
pip install -e .
