### ISSUE TITLE
windows10 python 312 "fontconfig error"

### ISSUE THREAD

**Issue by juzha5** [drunkdream/weread-exporter#69]
C:\temp\Kindle\weread-exporter-main>python -m weread_exporter -b 4e132bc07263ff664e11075 -o epub -o pdf --force-login
Fontconfig error: Cannot load default config file: No such file: (null)
[2024-03-12 22:05:12,303][INFO]Exporting book 4e132bc07263ff664e11075
[2024-03-12 22:05:12,500][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/4e132bc07263ff664e11075
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\temp\Kindle\weread-exporter-main\weread_exporter\__main__.py", line 158, in <module>
    main()
  File "C:\temp\Kindle\weread-exporter-main\weread_exporter\__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\temp\Kindle\weread-exporter-main\weread_exporter\__main__.py", line 85, in async_main
    await page.launch(headless=args.headless, force_login=args.force_login)
  File "C:\temp\Kindle\weread-exporter-main\weread_exporter\webpage.py", line 174, in launch
    chrome = self._check_chrome()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Kindle\weread-exporter-main\weread_exporter\webpage.py", line 167, in _check_chrome
    raise utils.ChromeNotInstalledError(
weread_exporter.utils.ChromeNotInstalledError: Please make sure `chrome` is installed, and the install path is added to PATH environment.
You can test that with `where chrome` command.

查了一下，好像font这个错很多，但是大部分都是linux下的解决方法，windows下没有头绪，是要在path增加font文件路径？

**Comment by whitewatercn** [comment]
weread_exporter.utils.ChromeNotInstalledError: Please make sure chrome is installed, and the install path is added to PATH environment.
You can test that with where chrome command.

你的报错似乎是因为没有安装chrome浏览器

**Comment by mecyl** [comment]
这个默认要调用你电脑上的chrome浏览器，如果你已经安装过了，要在windows环境变量path中加入chrome.exe可执行文件所在的路径

**Comment by Duducoco** [comment]
拷贝C:\Windows\Fonts目录到程序执行的目录下即可
