### ISSUE TITLE
总是显示超时，主页无法打开~~~

### ISSUE THREAD

**Issue by hzmagix** [drunkdream/weread-exporter#70]
总是显示超时，主页无法打开~~~实际上可以调用浏览器，但是无法自动打开内容。

I:\Program Files (x86)\weread-exporter-main>python -m weread_exporter -b ebd327f0718c8443ebdf735 -o epub
Fontconfig error: Cannot load default config file: No such file: (null)
[2024-03-15 22:38:08,977][INFO]Exporting book ebd327f0718c8443ebdf735
[2024-03-15 22:38:09,196][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/ebd327f0718c8443ebdf735
[2024-03-15 22:38:09,728][INFO]Browser listening on: ws://127.0.0.1:54490/devtools/browser/b69386b8-79fb-4c0b-bc11-a4ffdf297a77

(process:4720): GLib-GIO-WARNING **: 22:38:09.956: Unexpectedly, UWP app `Microsoft.OutlookForWindows_1.2023.1114.100_x64__8wekyb3d8bbwe' (AUMId `Microsoft.OutlookForWindows_8wekyb3d8bbwe!Microsoft.OutlookforWindows') supports 1 extensions but has no verbs

(process:4720): GLib-GIO-WARNING **: 22:38:10.025: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2312.33.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs

(process:4720): GLib-GIO-WARNING **: 22:38:10.332: Unexpectedly, UWP app `Clipchamp.Clipchamp_2.9.3.0_neutral__yxz26nhyzhsrt' (AUMId `Clipchamp.Clipchamp_yxz26nhyzhsrt!App') supports 41 extensions but has no verbs
[2024-03-15 22:38:11,429][INFO][WeReadWebPage] Current login user is 微信用户
[2024-03-15 22:38:11,429][INFO][WeReadWebPage] Inject cookie wr_name=%E5%BE%AE%E4%BF%A1%E7%94%A8%E6%88%B7
[2024-03-15 22:38:11,430][INFO][WeReadWebPage] Inject cookie wr_localvid=ff032c4081ef580b9ff02b8
[2024-03-15 22:38:11,432][INFO][WeReadWebPage] Inject cookie wr_rt=web%40UOkhaelbwjfqfmAGQ3r_AL
[2024-03-15 22:38:11,433][INFO][WeReadWebPage] Inject cookie wr_gender=0
[2024-03-15 22:38:11,435][INFO][WeReadWebPage] Inject cookie wr_pf=0
[2024-03-15 22:38:11,436][INFO][WeReadWebPage] Inject cookie wr_avatar=
[2024-03-15 22:38:11,437][INFO][WeReadWebPage] Inject cookie wr_skey=js_pEZ8M
[2024-03-15 22:38:11,439][INFO][WeReadWebPage] Inject cookie wr_vid=519405753
[2024-03-15 22:38:11,440][INFO][WeReadWebPage] Inject cookie wr_fp=2600317417
[2024-03-15 22:38:11,441][INFO][WeReadWebPage] Inject cookie wr_gid=231410492
[2024-03-15 22:38:42,126][ERROR]Launch book ebd327f0718c8443ebdf735 home page failed
Traceback (most recent call last):
  File "I:\Program Files (x86)\weread-exporter-main\weread_exporter\__main__.py", line 85, in async_main
    await page.launch(headless=args.headless, force_login=args.force_login)
  File "I:\Program Files (x86)\weread-exporter-main\weread_exporter\webpage.py", line 233, in launch
    await self.wait_for_avatar()
  File "I:\Program Files (x86)\weread-exporter-main\weread_exporter\webpage.py", line 280, in wait_for_avatar
    raise RuntimeError("Wait for avatar timeout")
RuntimeError: Wait for avatar timeout

**Comment by drunkdream** [comment]
登录了吗
