### ISSUE TITLE
175行 launch报错

### ISSUE THREAD

**Issue by HWT-WalterHu** [drunkdream/weread-exporter#81]
[2024-05-26 22:43:57,810][INFO]Exporting book 3f532e7071728d433f55284
[2024-05-26 22:43:58,070][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/3f532e7071728d433f55284
Traceback (most recent call last):
  File "/Users/mac/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mac/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mac/pyprojects/weread-exporter/weread_exporter/__main__.py", line 158, in <module>
    main()
  File "/Users/mac/pyprojects/weread-exporter/weread_exporter/__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "/Users/mac/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mac/pyprojects/weread-exporter/weread_exporter/__main__.py", line 85, in async_main
    await page.launch(headless=args.headless, force_login=args.force_login)
  File "/Users/mac/pyprojects/weread-exporter/weread_exporter/webpage.py", line 175, in launch
    self._browser = await pyppeteer.launch(
  File "/Users/mac/opt/anaconda3/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/Users/mac/opt/anaconda3/lib/python3.9/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/Users/mac/opt/anaconda3/lib/python3.9/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by HWT-WalterHu** [comment]
同样的操作，windows可以打开网页。但是mac弹出的chrome是空白

**Comment by drunkdream** [comment]
chrome版本是多少
