### ISSUE TITLE
已扫描登陆就报错

### ISSUE THREAD

**Issue by onion0835** [drunkdream/weread-exporter#85]
(venv) PS D:\A-projects\pythonProject\weread-exporter-main> python -m weread_exporter -b a95323b0727dee1aa95b457 -o epub -o pdf   --load-timeout=800
Fontconfig error: Cannot load default config file: No such file: (null)
[2024-06-04 17:00:01,517][INFO]Exporting book a95323b0727dee1aa95b457
[2024-06-04 17:00:01,736][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/a95323b0727dee1aa95b457
[2024-06-04 17:00:02,268][INFO]Browser listening on: ws://127.0.0.1:42575/devtools/browser/595b5efa-b1a2-410c-bb32-dced066f334f

(process:24076): GLib-GIO-WARNING **: 17:00:03.647: Unexpectedly, UWP app `Microsoft.OutlookForWindows_1.2024.516.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.OutlookForWindows_8wekyb3d8bbwe!Microsoft.OutlookforWindows') supports 4 ext
ensions but has no verbs
[2024-06-04 17:00:06,119][INFO][WeReadExporter] Check chapter 2/书名页
[2024-06-04 17:00:06,119][INFO][WeReadExporter] File cache\a95323b0727dee1aa95b457\chapters\1-2.md not exist
[2024-06-04 17:00:06,120][INFO][WeReadWebPage] Go to chapter 2
[2024-06-04 17:00:06,127][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/a95323b0727dee1aa95b457kc81322c012c81e728d9d180
[2024-06-04 17:00:06,408][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/31.a560e5a1.js
[2024-06-04 17:00:06,478][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-04 17:00:06,480][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-04 17:00:06,480][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-04 17:00:06,481][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.e668081e.js
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\A-projects\pythonProject\weread-exporter-main\weread_exporter\__main__.py", line 158, in <module>
    main()
  File "D:\A-projects\pythonProject\weread-exporter-main\weread_exporter\__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "C:\Users\hp11\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\A-projects\pythonProject\weread-exporter-main\weread_exporter\__main__.py", line 92, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "D:\A-projects\pythonProject\weread-exporter-main\weread_exporter\export.py", line 353, in export_markdown
    markdown = await self._page.get_markdown()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A-projects\pythonProject\weread-exporter-main\weread_exporter\webpage.py", line 396, in get_markdown
    result = await self._page.evaluate(script)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A-projects\pythonProject\weread-exporter-main\venv\Lib\site-packages\pyppeteer\page.py", line 1117, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A-projects\pythonProject\weread-exporter-main\venv\Lib\site-packages\pyppeteer\frame_manager.py", line 308, in evaluate
    return await context.evaluate(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A-projects\pythonProject\weread-exporter-main\venv\Lib\site-packages\pyppeteer\execution_context.py", line 53, in evaluate
    handle = await self.evaluateHandle(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A-projects\pythonProject\weread-exporter-main\venv\Lib\site-packages\pyppeteer\execution_context.py", line 92, in evaluateHandle
    raise ElementHandleError(
pyppeteer.errors.ElementHandleError: Evaluation failed: ReferenceError: canvasContextHandler is not defined
    at __pyppeteer_evaluation_script__:1:1
[2024-06-04 17:00:16,076][INFO]terminate chrome process...

**Comment by snow-engine** [comment]
遇到同样的问题了，您有解决么？

另外，我先登录，然后再启动也不行，没有读取已经存在的认证信息，您会有这个问题么？
