### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by kttddr** [drunkdream/weread-exporter#86]
$ python -m weread_exporter -b 08232ac0720befa90825d88 -o epub
[2024-06-10 11:02:14,585][INFO]Exporting book 08232ac0720befa90825d88
[2024-06-10 11:02:14,868][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/08232ac0720befa90825d88
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kttdd\Desktop\weread-exporter-main\weread_exporter\__main__.py", line 158, in <module>
    main()
  File "C:\Users\kttdd\Desktop\weread-exporter-main\weread_exporter\__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "C:\Python\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kttdd\Desktop\weread-exporter-main\weread_exporter\__main__.py", line 85, in async_main
    await page.launch(headless=args.headless, force_login=args.force_login)
  File "C:\Users\kttdd\Desktop\weread-exporter-main\weread_exporter\webpage.py", line 174, in launch
    chrome = self._check_chrome()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kttdd\Desktop\weread-exporter-main\weread_exporter\webpage.py", line 167, in _check_chrome
    raise utils.ChromeNotInstalledError(
weread_exporter.utils.ChromeNotInstalledError: Please make sure `chrome` is installed, and the install path is added to PATH environment.
You can test that with `where chrome` command.
Fontconfig error: Cannot load default config file: No such file: (null)

**Comment by xfgy1234** [comment]
安装chrome，然后把chrome添加到环境变量。前面的issue有提到具体的解决办法，可以找一下

**Comment by kttddr** [comment]
> 安装chrome，然后把chrome添加到环境变量。前面的issue有提到具体的解决办法，可以找一下

添加完控制变量后，可以运行了。想再请教下怎么登录。因为没有登录，在试读截至的地方，无限重复
$ python -m weread_exporter -b 08232ac0720befa90825d88 -o epub
[2024-06-13 20:44:10,314][INFO]Exporting book 08232ac0720befa90825d88
[2024-06-13 20:44:10,578][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/08232ac0720befa90825d88
[2024-06-13 20:44:11,151][INFO]Browser listening on: ws://127.0.0.1:3974/devtools/browser/c2175f4a-8047-4f12-a646-33c297ced7f6
[2024-06-13 20:44:12,948][INFO][WeReadExporter] Check chapter 41/▒▒Ȩ▒▒Ϣ
[2024-06-13 20:44:12,953][INFO][WeReadExporter] Check chapter 42/▒▒▒ݴ▒▒▒ĳɳ▒֮▒▒
[2024-06-13 20:44:12,953][INFO][WeReadExporter] Check chapter 43/▒▒1▒▒▒▒▒▒
[2024-06-13 20:44:12,953][INFO][WeReadExporter] Check chapter 44/▒▒▒▒
[2024-06-13 20:44:12,954][INFO][WeReadExporter] Check chapter 45/ǰ▒▒
[2024-06-13 20:44:12,954][INFO][WeReadExporter] Check chapter 46/▒▒л
[2024-06-13 20:44:12,954][INFO][WeReadExporter] Check chapter 47/▒▒▒▒
[2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 48/▒▒һ▒▒▒▒ ▒▒▒▒֪ʶ
[2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 49/▒▒1▒▒ ▒▒
[2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 50/▒▒2▒▒ ▒▒▒▒▒ͼ▒▒▒▒▒▒▒▒▒
[2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 51/▒▒3▒▒ ▒б▒▒▒
[2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 52/▒▒4▒▒ ▒▒▒▒▒б▒
[2024-06-13 20:44:12,956][INFO][WeReadExporter] File cache\08232ac0720befa90825d88\chapters\12-52.md not exist
[2024-06-13 20:44:12,956][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:12,962][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:13,231][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/31.a560e5a1.js
[2024-06-13 20:44:13,330][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:13,333][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:13,333][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:13,334][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-13 20:44:19,273][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:19,279][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:19,763][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:19,763][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:19,764][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:19,764][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-13 20:44:24,576][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:24,582][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-13 20:44:30,521][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:30,528][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-13 20:44:36,919][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:36,922][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:38,449][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:38,449][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:38,450][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:38,450][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-13 20:44:43,042][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:43,050][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-13 20:44:49,392][INFO][WeReadWebPage] Go to chapter 52
[2024-06-13 20:44:49,399][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83
[2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js
[2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js
[2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css
[2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js

**Comment by yibajianghudao** [comment]
尝试一下readme 里面的 --force-login true

**Comment by yibajianghudao** [comment]
> > 安装chrome，然后把chrome添加到环境变量。前面的issue有提到具体的解决办法，可以找一下
> 
> 添加完控制变量后，可以运行了。想再请教下怎么登录。因为没有登录，在试读截至的地方，无限重复 $ python -m weread_exporter -b 08232ac0720befa90825d88 -o epub [2024-06-13 20:44:10,314][INFO]Exporting book 08232ac0720befa90825d88[2024-06-13 20:44:10,314][信息]导出书 08232ac0720befa90825d88 [2024-06-13 20:44:10,578][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/08232ac0720befa90825d88[2024-06-13 20:44:10,578][信息][我们读网页]启动 url https://weread.qq.com/web/bookDetail/08232ac0720befa90825d88 [2024-06-13 20:44:11,151][INFO]Browser listening on: ws://127.0.0.1:3974/devtools/browser/c2175f4a-8047-4f12-a646-33c297ced7f6[2024-06-13 20:44:11,151][信息]浏览器侦听时间：ws://127.0.0.1:3974/devtools/browser/c2175f4a-8047-4f12-a646-33c297ced7f6 [2024-06-13 20:44:12,948][INFO][WeReadExporter] Check chapter 41/▒▒Ȩ▒▒Ϣ[2024-06-13 20:44:12,948][信息][WeRead出口商]查看第 41 章/▒▒全书▒▒Ϣ [2024-06-13 20:44:12,953][INFO][WeReadExporter] Check chapter 42/▒▒▒ݴ▒▒▒ĳɳ▒֮▒▒[2024-06-13 20:44:12,953][信息][WeRead出口商]查看第42章/▒▒▒▒▒▒ijɳ▒֮▒▒ [2024-06-13 20:44:12,953][INFO][WeReadExporter] Check chapter 43/▒▒1▒▒▒▒▒▒[2024-06-13 20:44:12,953][信息][WeRead出口商]查看第 43/▒▒1 章▒▒▒▒▒▒ [2024-06-13 20:44:12,953][INFO][WeReadExporter] Check chapter 44/▒▒▒▒[2024-06-13 20:44:12,953][信息][WeRead出口商]查看第 44 章/▒▒▒▒ [2024-06-13 20:44:12,954][INFO][WeReadExporter] Check chapter 45/ǰ▒▒[2024-06-13 20:44:12,954][信息][WeRead出口商]查看第45章/ǰ▒▒ [2024-06-13 20:44:12,954][INFO][WeReadExporter] Check chapter 46/▒▒л[2024-06-13 20:44:12,954][信息][WeRead出口商]查看第 46 章/▒▒л [2024-06-13 20:44:12,954][INFO][WeReadExporter] Check chapter 47/▒▒▒▒[2024-06-13 20:44:12,954][信息][WeRead出口商]查看第 47 章/▒▒▒▒▒ [2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 48/▒▒һ▒▒▒▒ ▒▒▒▒֪ʶ[2024-06-13 20:44:12,955][信息][WeRead出口商]查看第48章/▒▒һ▒▒▒▒▒ ▒▒▒֪ʁ [2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 49/▒▒1▒▒ ▒▒[2024-06-13 20:44:12,955][信息][WeRead出口商]查看第 49 章/▒▒1▒▒ ▒▒ [2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 50/▒▒2▒▒ ▒▒▒▒▒ͼ▒▒▒▒▒▒▒▒▒[2024-06-13 20:44:12,955][信息][WeRead出口商]查看第 50/▒▒2▒▒ ▒▒▒▒▒ͼ▒▒▒▒▒▒▒▒▒ [2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 51/▒▒3▒▒ ▒б▒▒▒[2024-06-13 20:44:12,955][信息][WeRead出口商]查看第 51 章/▒▒3▒▒ ▒б▒▒▒▒ [2024-06-13 20:44:12,955][INFO][WeReadExporter] Check chapter 52/▒▒4▒▒ ▒▒▒▒▒б▒[2024-06-13 20:44:12,955][信息][WeRead出口商]查看第 52 章/▒▒4▒▒ ▒▒▒▒▒б▒ [2024-06-13 20:44:12,956][INFO][WeReadExporter] File cache\08232ac0720befa90825d88\chapters\12-52.md not exist[2024-06-13 20:44:12,956][信息][WeRead出口商]文件缓存\08232ac0720befa90825d88\chapters\12-52.md 不存在 [2024-06-13 20:44:12,956][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:12,956][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:12,962][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:12,962][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:13,231][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/31.a560e5a1.js[2024-06-13 20:44:13,231][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/31.a560e5a1.js [2024-06-13 20:44:13,330][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:13,330][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:13,333][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:13,333][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:13,333][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:13,333][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:13,334][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:13,334][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js [2024-06-13 20:44:19,273][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:19,273][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:19,279][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:19,279][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:19,763][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:19,763][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:19,763][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:19,763][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:19,764][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:19,764][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:19,764][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:19,764][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js [2024-06-13 20:44:24,576][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:24,576][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:24,582][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:24,582][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:26,120][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:26,120][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:26,120][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:26,120][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:26,120][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js [2024-06-13 20:44:30,521][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:30,521][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:30,528][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:30,528][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:32,091][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:32,091][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:32,091][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:32,091][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:32,091][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js [2024-06-13 20:44:36,919][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:36,919][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:36,922][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:36,922][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:38,449][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:38,449][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:38,449][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:38,449][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:38,450][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:38,450][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:38,450][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:38,450][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js [2024-06-13 20:44:43,042][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:43,042][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:43,050][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:43,050][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:44,611][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:44,611][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:44,611][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:44,611][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:44,611][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js [2024-06-13 20:44:49,392][INFO][WeReadWebPage] Go to chapter 52[2024-06-13 20:44:49,392][信息][我们读网页]转到第 52 章 [2024-06-13 20:44:49,399][INFO][WeReadWebPage] Fetch url https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83[2024-06-13 20:44:49,399][信息][我们读网页]获取网址 https://weread.qq.com/web/reader/08232ac0720befa90825d88k9a132c802349a1158154a83 [2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js[2024-06-13 20:44:50,986][信息][我们读网页]获取网址 https://midas.gtimg.cn/midas/minipay_v2/jsapi/cashier.js [2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://cdn.weread.qq.com/web/wpa.js[2024-06-13 20:44:50,986][信息][我们读网页]获取网址 https://cdn.weread.qq.com/web/wpa.js [2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css[2024-06-13 20:44:50,986][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/css/app.d943696f.css [2024-06-13 20:44:50,986][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js[2024-06-13 20:44:50,986][信息][我们读网页]获取网址 https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js

尝试一下readme 里面的 --force-login true
