### ISSUE TITLE
md文件下载好了，但是不能合成epub，报错load selector timeout

### ISSUE THREAD

**Issue by 42689LZY** [drunkdream/weread-exporter#88]
![error1](https://github.com/drunkdream/weread-exporter/assets/172606249/b9ae2506-4f0a-4a56-b3c1-73f05fe58c12)
![erro12](https://github.com/drunkdream/weread-exporter/assets/172606249/c5de0472-2dfa-4d09-93e2-1bd4cfc8b69b)
2024-06-17 15:10:22,032][INFO][WeReadWebPage] Fetch url https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/js/app.aecf9799.js
[2024-06-17 15:11:26,196][INFO][WeReadWebPage] Current html saved to webpage.html
[2024-06-17 15:11:28,280][INFO][WeReadWebPage] Current screenshot saved to screenshot.jpg
[2024-06-17 15:11:28,281][INFO][WeReadWebPage] load selector timeout
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\weread-exporter-main\weread-exporter-main\weread_exporter\__main__.py", line 158, in <module>
    main()
  File "D:\weread-exporter-main\weread-exporter-main\weread_exporter\__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\weread-exporter-main\weread-exporter-main\weread_exporter\__main__.py", line 92, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "D:\weread-exporter-main\weread-exporter-main\weread_exporter\export.py", line 353, in export_markdown
    markdown = await self._page.get_markdown()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\weread-exporter-main\weread-exporter-main\weread_exporter\webpage.py", line 395, in get_markdown
    result = await self._page.evaluate(script)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Roaming\Python\Python312\site-packages\pyppeteer\page.py", line 1117, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Roaming\Python\Python312\site-packages\pyppeteer\frame_manager.py", line 308, in evaluate
    return await context.evaluate(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Roaming\Python\Python312\site-packages\pyppeteer\execution_context.py", line 53, in evaluate
    handle = await self.evaluateHandle(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Roaming\Python\Python312\site-packages\pyppeteer\execution_context.py", line 92, in evaluateHandle
    raise ElementHandleError(
pyppeteer.errors.ElementHandleError: Evaluation failed: ReferenceError: canvasContextHandler is not defined
    at __pyppeteer_evaluation_script__:1:1
[2024-06-17 15:11:28,286][INFO]terminate chrome process...
PS D:\weread-exporter-main\weread-exporter-main>

**Comment by shengjiangfeng** [comment]
这个我fix了，是代码里有个load的timeout是10S, 把这个timeout时间调大就行
