### ISSUE TITLE
大佬们帮忙看下这个问题 json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 3599 (char 3598)

### ISSUE THREAD

**Issue by wuqh1990** [drunkdream/weread-exporter#95]
执行一下脚本到目录页面的时候就开始报错

python -m weread_exporter -b 975325307210fc0b9754017 -o epub -o pdf

![image](https://github.com/user-attachments/assets/b6b38a98-6a83-4a45-8166-6c14b1e6d6b2)

(process:27456): GLib-GIO-WARNING **: 09:54:36.500: Unexpectedly, UWP app `Clipchamp.Clipchamp_3.1.11120.0_neutral__yxz26nhyzhsrt' (AUMId `Clipchamp.Clipchamp_yxz26nhyzhsrt!App') supports 41 extensions but has no verbs
[2024-08-12 09:54:36,793][INFO]Browser listening on: ws://127.0.0.1:49853/devtools/browser/7a9c4d78-7345-4c4f-8eeb-87ecee9333e6
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\LocalProject\weread-exporter-main\weread-exporter-main\weread_exporter\__main__.py", line 158, in <module>
    main()
  File "E:\LocalProject\weread-exporter-main\weread-exporter-main\weread_exporter\__main__.py", line 154, in main
    loop.run_until_complete(async_main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\LocalProject\weread-exporter-main\weread-exporter-main\weread_exporter\__main__.py", line 92, in async_main
    await exporter.export_markdown(args.load_timeout, args.load_interval)
  File "E:\LocalProject\weread-exporter-main\weread-exporter-main\weread_exporter\export.py", line 306, in export_markdown
    meta_data = await self._load_meta_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\LocalProject\weread-exporter-main\weread-exporter-main\weread_exporter\export.py", line 46, in _load_meta_data
    self._meta_data = await self._page.get_book_info()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\LocalProject\weread-exporter-main\weread-exporter-main\weread_exporter\webpage.py", line 45, in get_book_info
    data = json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 3599 (char 3598)

**Comment by Oshibuki** [comment]
![图片](https://github.com/user-attachments/assets/f37bb7e6-5ec2-4526-99a0-0c0fac5761cd)
信息截断补全出错，需要补代码中选中的这一句
data = data[:-1] + '"' + data[-1:] + '}}}'
