### ISSUE TITLE
反复循环 

### ISSUE THREAD

**Issue by yaylo** [drunkdream/weread-exporter#99]
PS C:\Users\fuw> python -m weread_exporter -b 41c32e507232785e41c35a3 -o pdf --load-timeout=300 --force-login
Fontconfig error: Cannot load default config file: No such file: (null)

(process:15312): GLib-GIO-WARNING **: 20:47:44.764: Unexpectedly, UWP app `HaukeGtze.NotepadEditor_1.8420.1.0_x64__6bk20wvc8rfx2' (AUMId `HaukeGtze.NotepadEditor_6bk20wvc8rfx2!notepad') supports 182 extensions but has no verbs
[2024-09-01 20:47:45,155][INFO]Exporting book 41c32e507232785e41c35a3

(process:15312): GLib-GIO-WARNING **: 20:47:45.437: Unexpectedly, UWP app `Microsoft.OutlookForWindows_1.2024.319.300_x64__8wekyb3d8bbwe' (AUMId `Microsoft.OutlookForWindows_8wekyb3d8bbwe!Microsoft.OutlookforWindows') supports 4 extensions but has no verbs
[2024-09-01 20:47:45,502][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/41c32e507232785e41c35a3
[2024-09-01 20:47:46,058][INFO]Browser listening on: ws://127.0.0.1:50055/devtools/browser/b4395224-e9a6-4c68-9dea-5fb5912109e4

(process:15312): GLib-GIO-WARNING **: 20:47:46.296: Unexpectedly, UWP app `Clipchamp.Clipchamp_3.1.11520.0_neutral__yxz26nhyzhsrt' (AUMId `Clipchamp.Clipchamp_yxz26nhyzhsrt!App') supports 41 extensions but has no verbs

(process:15312): GLib-GIO-WARNING **: 20:47:46.345: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2407.3.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs
[2024-09-01 20:47:49,609][INFO][WeReadWebPage] Update cookie wr_skey=ZUnqkXQ_
[2024-09-01 20:47:49,782][INFO][WeReadWebPage] Current login ########
[2024-09-01 20:47:49,782][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,782][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,782][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,797][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,797][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,797][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,797][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,797][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,813][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:47:49,813][INFO][WeReadWebPage] Inject cookie ########
[2024-09-01 20:48:20,928][ERROR]Launch book 41c32e507232785e41c35a3 home page failed
Traceback (most recent call last):
  File "C:\Users\fuw\weread-exporter-main\weread_exporter\__main__.py", line 85, in async_main
    await page.launch(headless=args.headless, force_login=args.force_login)
  File "C:\Users\fuw\weread-exporter-main\weread_exporter\webpage.py", line 233, in launch
    await self.wait_for_avatar()
  File "C:\Users\fuw\weread-exporter-main\weread_exporter\webpage.py", line 282, in wait_for_avatar
    raise RuntimeError("Wait for avatar timeout")
RuntimeError: Wait for avatar timeout
[2024-09-01 20:48:22,975][INFO][WeReadWebPage] Launch url https://weread.qq.com/web/bookDetail/41c32e507232785e41c35a3
[2024-09-01 20:48:23,529][INFO]Browser listening on: ws://127.0.0.1:50232/devtools/browser/15576f24-1515-4db8-aad5-0c734050aebf
[2024-09-01 20:48:26,462][INFO][WeReadWebPage] Current login########
[2024-09-01 20:48:26,463][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,467][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,472][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,474][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,477][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,482][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,485][INFO][WeReadWebPage] Inject cookie########

就是这样反复循环不登陆可以 登陆后就用不了
[2024-09-01 20:48:26,488][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,490][INFO][WeReadWebPage] Inject cookie########
[2024-09-01 20:48:26,493][INFO][WeReadWebPage] Inject cookie########

**Comment by yaylo** [comment]
换了个账号可以了
